### ISSUE TITLE
License text of monorepo packages: Read from repository root?

### ISSUE THREAD

**Issue by codepunkt** [codepunkt/webpack-license-plugin#2]
When a package has no licenseText, but a github repository URL, we could check the repository root for a `/licen[cs]e/i` file and use its text as the licenseText if one exists.

**Comment by w3nda** [comment]
@codepunkt we're currently seeing this when using the following package: https://github.com/vercel/swr
There is no license data in sub packages, any suggestions?

**Comment by codepunkt** [comment]
Open pull requests for license info. Should be a mandatory field in package.json, but isn’t.
