### ISSUE TITLE
Clarify selection

### ISSUE THREAD

**Issue by peteruithoven** [codepunkt/webpack-license-plugin#400]
This is mostly a documentation question.

I noticed that [webpack-license-plugin](https://github.com/codepunkt/webpack-license-plugin) results in quite a few less "items" than [license-checker](https://www.npmjs.com/package/license-checker), even when I filter license-checker on just production and just direct dependencies. 
I do clearly see that at least all the import's I'm doing in my code are included by [webpack-license-plugin](https://github.com/codepunkt/webpack-license-plugin). I even find dependencies of those imports. 
I'm assuming [license-checker](https://www.npmjs.com/package/license-checker) does not do tree shaking, so that might explain a lot. 
Update: [license-checker's direct option doesn't work](https://github.com/davglass/license-checker/issues/191)
I'm not asking to explain the differences, but a bit more info on how the selection works would be very interesting. Is it really as simple as what's gets included in the build, and thus gets distributed, gets included in the list? 

I'm hoping to get some legal advice soon, but shouldn't code that's used to create the project, but isn't distributed, also be included? Things like eslint, webpack loaders, in my case vue-cli relates packages?
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software

But maybe the idea is that we're not copying things like eslint / webpack loaders etc even though we are using it locally. 

[webpack-license-plugin](https://github.com/codepunkt/webpack-license-plugin): 
- MIT: 65
- BSD-3-Clause: 7
- ISC: 3
- Apache-2.0: 1
- 0BSD: 1

[license-checker](https://www.npmjs.com/package/license-checker):
```
$ npx license-checker  --summary --production --excludePrivatePackages 
├─ MIT: 251
├─ ISC: 31
├─ BSD-2-Clause: 16
├─ BSD-3-Clause: 12
├─ Apache-2.0: 4
├─ CC0-1.0: 2
├─ 0BSD: 2
├─ (MIT OR CC0-1.0): 2
└─ MIT*: 1

$ npx license-checker --summary --production --excludePrivatePackages --direct
├─ MIT: 290
├─ ISC: 24
├─ BSD-2-Clause: 14
├─ BSD-3-Clause: 12
├─ Apache-2.0: 4
├─ (MIT OR Apache-2.0): 1
├─ BSD*: 1
├─ CC0-1.0: 1
├─ 0BSD: 1
├─ (MIT OR CC0-1.0): 1
└─ MIT*: 1
```

**Comment by peteruithoven** [comment]
Seeing that [license-checker's direct option doesn't work](https://github.com/davglass/license-checker/issues/191), plus it not doing tree shaking probably explains the difference. 

Because this plugin is a webpack plugin I'm assuming it benefits from tree-shaking?

**Comment by codepunkt** [comment]
Hey Peter!

That's an awesome question! Your assumptions are correct. The only way to just scan the dependencies that are actually used in a webpack build output (after tree-shaking and other optimizations) is by actually using webpack to do that.

This plugin hooks into the build process and gets the list of all files that are included (either as a whole, or partially) in the build result. It then maps these file paths to node_modules and retrieves the packages and their versions.

> But maybe the idea is that we're not copying things like eslint / webpack loaders etc even though we are using it locally.

I deal with license compliance in my company from a technical point of view. The general consesus is that you only need to provide license information for the open source projects that you "distribute".

For JavaScript/Web-based frontends that is typically the code that's loaded into the browser in production. Code that is only used for development, build or testing purposes is usually not distributed - and thus does not need to be listed in a "bill of materials".

However, I'm not a lawyer and the law might be different in different countries. If you need legal advice, contact a lawyer 😀

**Comment by peteruithoven** [comment]
Thanks @codepunkt that clarifies a lot. 

Another confirmation that this works is that the development build contains more packages + licenses than the production build. Looking at those packages they are for things like like hot reloading.

**Comment by peteruithoven** [comment]
I hope one day we'll see some good info on sites like: https://opensource.guide

Relevant issues:
- https://github.com/github/opensource.guide/issues/1084
- https://github.com/github/opensource.guide/issues/1761
