### ISSUE TITLE
use replenishDefaultLicenseTexts in specific license types

### ISSUE THREAD

**Issue by zoltan-mihalyi** [codepunkt/webpack-license-plugin#422]
If I am correct, the Apache 2.0 license requires the license text to be included, but others don't.
It would be great if `replenishDefaultLicenseTexts` could be a function, which decides what license should be replenished

**Comment by codepunkt** [comment]
You could also do that by parsing the resulting JSON to an `additionalFile`, right?

**Comment by codepunkt** [comment]
@zoltan-mihalyi Are you still interested in this?

**Comment by zoltan-mihalyi** [comment]
@codepunkt The MIT license requires the license notice to be included, so no, thank you!
