### ISSUE TITLE
WARNING in Conflict: Multiple assets emit different content to the same filename oss-licenses.json

### ISSUE THREAD

**Issue by fabis94** [codepunkt/webpack-license-plugin#491]
I'm using parallel-webpack to run multiple webpack builds at the same time. Both builds, however, output license information to different files (oss-licenses-x.json and oss-licenses-y.json) and yet this warning still pops up. This makes me think that it occurs during the same build.

![image](https://user-images.githubusercontent.com/938316/115360168-0d15dd80-a1c8-11eb-8193-8ced6e42d241.png)

**Comment by codepunkt** [comment]
@fabis94 Do you have a reproducible example, preferrably with version `4.1.3`?

**Comment by codepunkt** [comment]
This is likely fixed by #619 

If it isn't, please open a new issue with a reproducible example based on the latest version of this plugin.
