### ISSUE TITLE
Enhancement: Add "includePackages" option

### ISSUE THREAD

**Issue by WIStudent** [codepunkt/webpack-license-plugin#541]
I am creating a hybrid android/ios app using [capacitor](https://capacitorjs.com/). The web part is built with webpack and uses webpack-license-plugin. But because of capacitor's structure, some dependencies like `@capacitor/android` are not imported in the web part, but used by the native wrapper around it. Because they are not imported in the web part, webpack-license-plugin cannot see these dependencies.

As a workaround I am using the following code to collect the licenses for a predefined list of packages:
```typescript
import LicenseMetaAggregator from 'webpack-license-plugin/dist/LicenseMetaAggregator';
import WebpackFileSystem from 'webpack-license-plugin/dist/WebpackFileSystem';
import fs from 'fs';
import PackageJsonReader from 'webpack-license-plugin/dist/PackageJsonReader';
import path from 'path';
import unacceptableLicenseTest from './unacceptableLicenseTest';

export const additionalPackages = async () => {
  const fileSystem = new WebpackFileSystem(fs);
  const alertAggregator = {
    addError: (message: string) => {
      throw new Error(message);
    },
    addWarning: () => {},
    flushAlerts: () => {}
  };
  const options = {
    additionalFiles: {},
    licenseOverrides: {},
    outputFilename: '',
    replenishDefaultLicenseTexts: true,
    unacceptableLicenseTest,
    excludedPackageTest: () => false
  };
  const licenseMetaAggregator = new LicenseMetaAggregator(fileSystem, alertAggregator, options, new PackageJsonReader(fileSystem));
  const modules = ['@capacitor/android', '@capacitor/ios'].map(m => path.dirname(require.resolve(`${m}/package.json`)));
  return await licenseMetaAggregator.aggregateMeta(modules);
};
```
The packages retuned by this function are then merged with the packages from webpack-license-plugin using the `additionalFiles` option:
```typescript
new LicensePlugin({
  additionalFiles: {
    'oss-licenses.json': async (packages) => {
      return JSON.stringify([...packages, ...(await additionalPackages())]);
    }
  }.
  replenishDefaultLicenseTexts: true,
  unacceptableLicenseTest
})
```

This works fine (it extracts the licenses correctly and throws errors for unacceptable licenses), but except for the moduleDirs source it is basicly the same code as inside the webpack-license-plugin. Therefore I would like to propose an additional option `includePackages` that allows to define a list of packages whose licenses should always be included in the license output.

**Comment by codepunkt** [comment]
I have not heard about that use-case before, but I think we could support that. 👍🏻

I'm not how we would locate the correct `package.json` and module root directoryfor varying repository setups like monorepos or otherwise nested node_module directories etc. We could probably use `require.resolve()` for that.

Would you mind providing a pull request?
