### ISSUE TITLE
CRA build with craco warns about multiple assets emitting to oss-licenses.json

### ISSUE THREAD

**Issue by thisgeek** [codepunkt/webpack-license-plugin#564]
In my case, I configure a create-react-app to use webpack-license-plugin via [craco](https://github.com/gsoft-inc/craco).

~Reproduction repository (git archive): git-repro.zip~ Edit: See correct zip archive in comments.

Running `yarn build` produces the following warning:

> Conflict: Multiple assets emit different content to the same filename oss-licenses.json

Similar to #491 and #435.

The current release of react-scripts (4.0.3) uses webpack@4.44.2.

Reverting to webpack-license-plugin@4.1.2 (which was before #510) does not resolve the issue.

**Comment by codepunkt** [comment]
@thisgeek `yarn build` in the example doesn't do anything, the example doesn't even have `webpack` or `webpack-license-plugin` installed.

Please provide a reproduction of this issue.

**Comment by thisgeek** [comment]
Thank for looking. My apologies. I sent you the wrong archive. Will recreate.

**Comment by thisgeek** [comment]
Here you go: [webpack-license-plugin-repro.zip](https://github.com/codepunkt/webpack-license-plugin/files/6924413/webpack-license-plugin-repro.zip)

**Comment by badeAdebayo** [comment]
any update on this? im seeing this issue as well

**Comment by codepunkt** [comment]
Should be fixed by #619
