### ISSUE TITLE
License file will not be generated(Conflict: Multiple assets emit different content to the same filename)

### ISSUE THREAD

**Issue by ddelkhosh** [codepunkt/webpack-license-plugin#581]
I test all sample usage that mentioned in README file in my Angular Project and all of them has this Error:

**Error: Conflict: Multiple assets emit different content to the same filename meta/3dParty-Licenses.json**

node v14.16.1
npm 6.14.13
webpack 5.44.0 
angular/cli 12.1.4

**Reproduction:** 
> ng new sampleProject
> npm i -D @angular-builders/custom-webpack
> npm i -D webpack-license-plugin

Change angular build architect in angular.json file to:
`"architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "./custom-webpack.config.js"
            },
           ...
          },
        },
}`

Add this plugin into custom-webpack.config.js file.

> ng build

**Comment by codepunkt** [comment]
Which version of the plugin are you using?

Do you have an example repository, using the latest version of this plugin, that reproduces this problem?

**Comment by ddelkhosh** [comment]
> Which version of the plugin are you using?
> 
> Do you have an example repository, using the latest version of this plugin, that reproduces this problem?

I use webpack-license-plugin 4.2.0

I have created this example repo:
https://github.com/ddelkhosh/webpack-license-plugin-test

runing: >ng build
reproduced this Error:
_Error: Conflict: Multiple assets emit different content to the same filename meta/3dParty-Licenses.json_

**Comment by techouse** [comment]
Got this error when I downgraded to `v4.0.0`

```
Error: Module.entryModule: Multiple entry modules are not supported by the deprecated API (Use the new ChunkGroup API)
```

**Comment by codepunkt** [comment]
@techouse does the problem persist with latest version?
