### ISSUE TITLE
Passing 2nd package.json/project

### ISSUE THREAD

**Issue by larsk2009** [codepunkt/webpack-license-plugin#682]
Hi,

Just wondering if it is possible to include a whole 2nd project/package.json file in the output as well?

The expected bevhaviour for me would be like if you ran the plugin in both the current project + the other project you want, and merged + deduplicated the output file.

I see the `includePackages` option but doesn't seem like that accepts a whole project right?

EDIT: I think I misunderstood how this works, and it will probably be very difficult to do this as you'd actually need to hook into the 2nd project as well. I'll just do that and serve both files separately I think.

**Comment by codepunkt** [comment]
That’s not possible out of the box and out of scope of this project. However, merging two or more JSON files based on the name and version keys should be rather straightforward, if required.

Thanks for your interest in the plugin! 👍🏻
