### ISSUE TITLE
Handling inconsistency between package.json and license text

### ISSUE THREAD

**Issue by benwiley4000** [codepunkt/webpack-license-plugin#690]
Has any thought been given to checking whether the found license text correctly corresponds to what's in the package.json? It seems like a package could easily include a license but accidentally keep the default ISC in the package.json.

I've never seen a JavaScript implementation of this but the Licensee ruby gem (licenseejs is different) can detect license information from text. https://github.com/licensee/licensee 

I'm thinking of implementing something myself to validate this but it seems like it could make sense for this functionality to be included in the plugin. That said it could take a long time to run so it would be something you would turn on with a special option.

**Comment by codepunkt** [comment]
Feel free to implement that functionality as a package and let me know when it's done.

I might be tempted to use the functionality in this plugin! 😏
