### ISSUE TITLE
Repository not included in output

### ISSUE THREAD

**Issue by pathmapper** [codepunkt/webpack-license-plugin#703]
https://github.com/perliedman/reproject/blob/f2c43f266e27d163f77aeafe1ebe9236f75b2677/package.json#L5

```json
"repository": "git@github.com:perliedman/reproject.git"
```

results in

![image](https://user-images.githubusercontent.com/20856381/148635036-0c029ee6-454c-4fcc-8d03-a9a8ff6cd52a.png)

Should this syntax be supported?

On
https://www.npmjs.com/package/reproject
the repository is included:

![image](https://user-images.githubusercontent.com/20856381/148635123-3a34654a-c42c-46e6-8312-f134657db24a.png)

**Comment by codepunkt** [comment]
Fixed by #718 

Thanks for reporting! If you need this before a new version is released, feel free to install directly from the commit in main branch.

**Comment by pathmapper** [comment]
@codepunkt thanks for the fix!
