### ISSUE TITLE
Build fails with unclear error message: "Error"

### ISSUE THREAD

**Issue by dekim24** [codepunkt/webpack-license-plugin#722]
I can't point to an actual Github repo / app (private repo) but you should be able to reproduce by doing the following:

- Install the dependency `@mapbox/fusspot@0.4.0`
- Try to run the plugin.

Actual behavior: The plugin errors out (expected) but the message shown is the very unclear string `Error`
Desired behavior: The error message is formatted properly: `License "BSD 2-Clause" for @mapbox/fusspot@0.4.0 is not a valid SPDX expression!`

I figured out the error message that wasn't being shown properly by going into into node_modules and add a `console.log(message);` here: https://github.com/codepunkt/webpack-license-plugin/blob/1f93db32c1df061fc923e6c3c729ee1825a85c14/src/WebpackAlertAggregator.ts#L11

I'm investigating further to try to figure out why this happened - wondering if there's something going wrong between <constructing the error array> and <displaying the final error message> when an error in this particular format is in the array.

**Comment by codepunkt** [comment]
@dekim24 Any progress?
