### ISSUE TITLE
Collecting licenses for monorepo packages when license is only in root level

### ISSUE THREAD

**Issue by yonayarin** [codepunkt/webpack-license-plugin#809]
Hi,
we are using 'swr' package  and lately we upgraded to the latest version (1.3.0) and got a new error during the build:

```WebpackLicensePlugin: Could not find license info for swr-infinite@0.0.1```

It seems the repo changed to a mono-repo causing an issue to collect the license for the sub-packages (since he only exists at the root level).

Are you going to detect cases like that or expect each package to have a license?

**Comment by codepunkt** [comment]
It would be nice if `license` was a mandatory field in `package.json`, but it isn’t.
We could implement workarounds in this package, but they would be brittle and error-prone. In addition, we would be implying an intention here (all sub-packages are supposed to be licensed like the monorepo root) that is not necessarily true.

Licenses have to be explicitly declared in packages. If they're not, they're basically `UNLICENSED` and cannot be used by any person or organization that depends on open source license compliance.
Please open pull requests in the respective repositories that copy the monorepo's license info to the individual packages.

**Comment by yonayarin** [comment]
Thanks for the fast response I have already opened a ticket for them.
https://github.com/vercel/swr/issues/2081

**Comment by codepunkt** [comment]
Chimed in with some basic advice. Hope that gets resolved soon, as it’s a very easy fix!
