### ISSUE TITLE
The package being build is not included in the output.

### ISSUE THREAD

**Issue by sebaspf** [codepunkt/webpack-license-plugin#845]
When building the code for redistributing (e.g. a frontend or a module), the dependencies and also the current package information must be included in the output file. As the final bundle includes both, the dependencies and the new code, all licences must be present. 

Steps to reproduce:
```sh
# From the repository root
cd test/e2e/example 
node ../../../node_modules/webpack/bin/webpack.js --config ../webpack.config.js
```
check that `test/e2e/example/dist/oss-licences.json` does not contain the example package (`webpack-license-plugin-test-example`)

**Comment by codepunkt** [comment]
I'm not sure this is required - most of the times I've seen this package in use you would not want the current package to be included. Do you use this to build libraries or what's your use case?

**Comment by codepunkt** [comment]
@sebaspf Are you following up on this PR? 😉

**Comment by sebaspf** [comment]
Sorry, long time no see ;-) Yes, I used it to generate a license disclaimer for the complete package, in that case you want to include the current license. I changed afterwards to the [license-webpack-plugin](https://www.npmjs.com/package/license-webpack-plugin) for that.

**Comment by codepunkt** [comment]
@sebaspf you could easily add that to the result manually, but I'm happy to see that a similar plugin helped!
