### ISSUE TITLE
Packages with no SPDX licence cause a build to fail

### ISSUE THREAD

**Issue by sebaspf** [codepunkt/webpack-license-plugin#856]
Enhancement

When building using dependencies with no SPDX license, the complete build fails as the check in [this line](https://github.com/codepunkt/webpack-license-plugin/blob/864eb9034c55be9ce35f33f2cfa7cfb2680d420b/src/LicenseIdentifier.ts#L53) fails generating an error. This behavior may be sometimes a problem when using many of these packages or when a different team handles the build configs. A possible solution could be to exclude them, but it requires an intervention for every new dependency. 

Anew option `handleNonSPDX` with the flowing values would be very handy for many applications:
+ `reject`: default, current behavior
+ `ignore`: do not list these packages in the output
+ `warning`: Add them to the output and show a warning.

**Comment by codepunkt** [comment]
Imagine your new option set to `ignore` and an important dependency mistakenly switching from _"Apache-2.0"_ to _"Apache 2.0"_ in a new version. This new version would then silently be excluded from the build output.

For reasons like this, implicitly excluding packages from the output is not something I'll likely ever support. If something is to be excluded from the output, it has to be explicitly defined with `excludedPackageTest` option.

I'm not entirely against allowing to choose error or warning semantics for packages with non-SPDX identifiers. However, you're the first to bring this up so I'll definitely wait for more feedback from other users before I add another option to the plugin.

May I ask what non-SPDX packages you're encountering and why you're using many of them?

**Comment by codepunkt** [comment]
Thanks 🤗

If you know what's happening with your internal packages, you need neither warnings nor errors. I suggest publishing internal packages in a specific namespace and then ignore those via `excludedPackageTest` option altogether. After all, they're both part of the software you're distributing and built by you or your company. In terms of open source licensing, there should be no difference to the source code you wrote on your project yourself.

Commercial packages are not open source either. You can choose to not list them in your `oss-licenses.json` file, or set them to a suitable license name using the `licenseOverrides` option.

Hope this helps!

**Comment by sebaspf** [comment]
Overriding a private license with some SPDX license would be a license violation and excluding the package from the list would implies I need to keep track of those dependencies separately with a second tool, increasing the maintenance work.

I think you mention an important point that was not really clear for me. The fact that "Commercial packages are not open source [...]" and that the default output file name is `oss-licences.json` makes me conclude that the philosophy of the plugin is to manage only the OSS included in the build and not all of the dependencies. This point is mentioned in the `Key Features` section of the README. If this is so, we will probably never reach a consensus.

**Comment by codepunkt** [comment]
You are right. This plugin is supposed to manage open source licenses to ease open source license compliance.

If you have commercial software that you include in your build output, you're probably paying for a license and have the right to use it in your project, so open source license compliance obligations do not apply.
