### ISSUE TITLE
Also NOTICE text should be included in the output

### ISSUE THREAD

**Issue by ccatterina** [codepunkt/webpack-license-plugin#937]
Hi,

I'd like to use this plugin to comply with a bunch libraries licenses that I include in my webapp bundle. But I noticed that the `NOTICE` file text is not included in the output although, from what I understand, it is a requirement of some licenses such as `Apache 2.0`. 

https://www.apache.org/licenses/LICENSE-2.0.txt  4.d
> If the Work includes a "NOTICE" text file as part of its
          distribution, then any Derivative Works that You distribute must
          include a readable copy of the attribution notices contained
          within such NOTICE file, excluding those notices that do not
          pertain to any part of the Derivative Works, in at least one
          of the following places: within a NOTICE text file distributed
          as part of the Derivative Works; within the Source form or
          documentation, if provided along with the Derivative Works; or,
          within a display generated by the Derivative Works, if and
          wherever such third-party notices normally appear. The contents
          of the NOTICE file are for informational purposes only and
          do not modify the License. You may add Your own attribution
          notices within Derivative Works that You distribute, alongside
          or as an addendum to the NOTICE text from the Work, provided
          that such additional attribution notices cannot be construed
          as modifying the License.

Do you think this feature could be added? I could also work on it and open a PR (I've never worked on a webpack plugin, but I can give it a try)

**Comment by codepunkt** [comment]
@ccatterina That sounds like a useful feature, thanks for reporting! Would love if you gave it a try! 😉

**Comment by ccatterina** [comment]
:+1:  I'll work on it in the next few days!

**Comment by codepunkt** [comment]
Released with v`4.5.0`
