### ISSUE TITLE
ESM build does not work in ES module config files

### ISSUE THREAD

**Issue by mrxz** [codepunkt/webpack-license-plugin#994]
I tried using the published ESM build in a Webpack project, but encountered errors directly upon importing the plugin using:
```JS
import LicensePlugin from 'webpack-license-plugin';
```

The error in question:
```
SyntaxError: Named export 'WebpackError' not found. The requested module 'webpack' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
```

Digging some more into it, there seems to be two issues with the current ESM bundle preventing it from being used in an ES Module webpack config file:

1. There are named imports from CommonJS modules, which aren't always supported by Node as the error message also indicates. TypeScript allows this just fine, hence it not causing issues when building. See https://github.com/microsoft/TypeScript/issues/54018
2. The bundle contains a CommonJS specific footer ([added here](https://github.com/codepunkt/webpack-license-plugin/blob/main/tsup.config.ts#L15)), which isn't valid in an ES module.

**Comment by codepunkt** [comment]
Thanks @mrxz!
