### ISSUE TITLE
`outputWriter` option

### ISSUE THREAD

**Issue by silverwind** [codepunkt/webpack-license-plugin#996]
Looking to replace [this plugin](https://github.com/microsoft/license-checker-webpack-plugin), which has an option `outputWriter` to pass a function that performs the output formatting. It could work like this:

```js
new LicensePlugin({
  outputFilename: 'licenses.txt',
  outputWriter: deps => deps.map(dep => dep.name).join('\n'),
});
```

I could contribute this feature if it's accepted.

**Comment by codepunkt** [comment]
You can do that using the `additionalFiles` option, overriding the default file name if you don't need a second file.
